name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "Initial Commit"
          TIME_RANGE: 'all_time'
          SHOW_PROJECTS: "True"
          SHOW_OS: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_DAYS_OF_WEEK: "True"
          COMMIT_BY_ME: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LINES_OF_CODE: "True"
